name: Security

on:
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

concurrency:
  group: security-${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  differential-security:
    name: Differential security
    uses: kanedasec/platform-workflows/.github/workflows/security-differential.yaml@463bfd537c536a12c8479b4b1b8ff712a4dc0b21
